### ISSUE TITLE
/modifyblacklist

### ISSUE THREAD

**Issue by Dimiikou** [paulzhng/UCUtils#17]
https://github.com/paulzhng/UCUtils/blob/master/src/main/java/de/fuzzlemann/ucutils/commands/faction/badfaction/blacklist/ModifyBlacklistCommand.java

Cause of the defined Usage, the command doesn't work.

It's always returning an error message sending the defined Usage

**Comment by paulzhng** [comment]
Should be fixed by 7ef602276daebf473f8fd39f46ad4959bc3b2ad2. Please confirm.

**Comment by Dimiikou** [comment]
Still the same error

**Comment by Dimiikou** [comment]
Fixxed in https://github.com/paulzhng/UCUtils/commit/0e199ade78cc670e93d46fe5270c4a522d8faae0
