### ISSUE TITLE
Revive - Kicked for Spamming (>Cooldown)

### ISSUE THREAD

**Issue by NichtTube** [paulzhng/UCUtils#4]
https://github.com/Fuzzlemann/UCUtils/blob/e6f81aa21730308a11bcd761f704739587bb69db/src/main/java/de/fuzzlemann/ucutils/events/ReviveEventHandler.java#L22

Hey,

ja, ich schon wieder - GitHub ist schon toll 👍 
Könntest du einen Cooldown von mind 0,5sek einbauen bei dem Medic Revive?
Leider wird nur jeder 4te Rechtsklick teilweise erkannt, weshalb wir Medics Rechtsklick bei Leichen gedrückt halten - manchmal wird man dann wegen "Kicked for Spamming" gekickt, weil so viele Commands gleichzeitig eingegeben werden.

Grüße
LeitenderNotarzt / NichtTube

**Comment by paulzhng** [comment]
fixed, see #6
