### ISSUE TITLE
Reinforcement / Takekomms Bug

### ISSUE THREAD

**Issue by MysteryMyron** [paulzhng/UCUtils#50]
**Reinforcement / Takekomms Bug**

(Zumindest bei mir) tritt momentan der Fehler auf, dass ich, wenn mir die Komms abgenommen werden, keine Reinforcements mehr absenden kann bis ich meine Komms wiederhabe. Das ist zwar richtig so, aber wenn man Minecraft neustartet, kann man trotzt abgenommener Komms Reinforcements absenden. Dies führte bereits zu mehreren Beschwerden, weshalb ich denke dass diese Info relativ wichtig ist...
Das ganze ist bei der neuesten Version von UCUtils (Habe es komplett neu installiert, /updateucutils und /refreshdata -v bzw. /refreshdata verwendet).

Vielen Dank!

**Comment by Dimiikou** [comment]
Hallo @MysteryMyron ,
Das liegt daran das die Variable welche sagt, ob du kommst hast oder nicht, bei jedem Neu starten deines Spieles neu Initialisiert wird.

Es gibt natürlich Lösungen welche das verhindern, ob das aber so nötig ist weiß ich wirklich nicht.
Kannst dich ja mal umhören, wenn das wirklich so sehr gewünscht wurde kann ich mich da sicherlich ransetzen.

Mit freundlichen Grüßen
Dimiikou

**Comment by MysteryMyron** [comment]
Okay, danke, ich werd mich mal umhören.
Wenn das genug Leute wünschen geb ich dir hier nochmal Bescheid, dann wär’s natürlich sehr nett wenn du da was umcodest. :)

Einen schönen Abend noch!
Liebe Grüße ~Myron

**Comment by Dimiikou** [comment]
Hey Myron,
Klingt nach einem Plan, machen wir so.

Dir auch!
Mit freundlichen Grüßen
Dimiikou
