### ISSUE TITLE
Weitere Bedingung für keine Kommunikationsmittel

### ISSUE THREAD

**Issue by lholl** [paulzhng/UCUtils#53]
Wenn der Akku des Handy leer ist erscheinen folgende Nachrichten:

- [ ] Wenn der Akku auf 0 sinkt: `Der Akku deines Handys ist leer.`
- [x] Wenn man versucht anzurufen: `Ihr Akku ist leer.`
- [x] Wenn man versucht das Handy anzuschalten: `Der Akku von deinem Handy ist leer.`

Die erste Nachricht ist noch nicht im [CommunicationsChecker](https://github.com/paulzhng/UCUtils/blob/master/src/main/java/de/fuzzlemann/ucutils/checks/CommunicationsChecker.java) enthalten.

**Comment by Dimiikou** [comment]
Mache ich sobald ich zuhause bin!

**Comment by Dimiikou** [comment]
Wobei, ich sehe hierbei das Problem das du ja allgemein auch ohne Akku reinforcements etc. machen darfst, würde das mit dem Akku denke eher ganz entfernen, da als Komms gewertet wird solange du ein Handy dabei hast (Akku egal)

**Comment by lholl** [comment]
Ok, und wie sieht es damit aus, ob das Handy eingeschaltet sein muss für Reinforcements?

**Comment by Dimiikou** [comment]
Soweit ich weiß auch nicht, du musst es nur dabei haben

**Comment by lholl** [comment]
Ja das stimmt, aber wäre es nicht ein sinnvolles Feature wenn man mit einem ausgeschaltetem Handy auch keine Reinforcements machen kann? Services gehen mit ausgeschaltetem Handy nicht.
Wenn nicht, dann pass ich den [CommunicationsChecker](https://github.com/paulzhng/UCUtils/blob/master/src/main/java/de/fuzzlemann/ucutils/checks/CommunicationsChecker.java) nochmal an und nehme die Fälle für keinen Akku und An/Aus raus.

**Comment by Dimiikou** [comment]
Ergibt als Feauture Sinn, aber aus Spieltechnischem Sinne garnicht. Man sollte schon seine maximalen Möglichkeiten nutzen können und nicht durch UCUtils (Gedacht um das Spielerlwbnis zu erleichtern) eingeschränkt werden. Denke ich schicke eine PR um das zu entfernen wenn ich wieder Zuhause bin (Sonntag)

**Comment by lholl** [comment]
Neue Version wurde mit altem [CommunicationsChecker ](https://github.com/paulzhng/UCUtils/blob/master/src/main/java/de/fuzzlemann/ucutils/checks/CommunicationsChecker.java) veröffentlicht... Trotzdem noch Akku und Handy an/aus Bedingung entfernen oder erstmal lassen?
